/**
 * React hook that is used to mark the block wrapper element.
 *
 * @see https://developer.wordpress.org/block-editor/reference-guides/packages/packages-block-editor/#useblockprops
 */
import { useBlockProps } from '@wordpress/block-editor';

/**
 * The save function defines the way in which the different attributes should
 * be combined into the final markup, which is then serialized by the block
 * editor into `post_content`.
 *
 * @see https://developer.wordpress.org/block-editor/reference-guides/block-api/block-edit-save/#save
 *
 * @return {Element} Element to render.
 */
export default function save({ attributes }) {
	const {
		blockId,
		tocTitle,
		supportedHeadings,
		showHierarchy,
		showNumbering,
		collapsibleOnMobile,
		smoothScroll,
		stickyMode,
		containerBackgroundColor,
		containerWidth,
		containerPadding,
		containerMargin,
		containerBorderStyle,
		containerBorderWidth,
		containerBorderColor,
		containerBorderRadius,
		titleColor,
		titleFontSize,
		titleFontWeight,
		titlePadding,
		listColor,
		listFontSize,
		additionalCssClass
	} = attributes;

	const blockProps = useBlockProps.save({
		className: `${additionalCssClass || ''} ${stickyMode ? 'sticky-mode' : ''} ${smoothScroll ? 'smooth-scroll' : ''} ${collapsibleOnMobile ? 'collapsible-mobile' : ''}`.trim(),
		'data-block-id': blockId,
		'data-supported-headings': JSON.stringify(supportedHeadings),
		'data-show-hierarchy': showHierarchy,
		'data-show-numbering': showNumbering,
		'data-smooth-scroll': smoothScroll,
		style: {
			'--list-item-style': containerBackgroundColor,
			backgroundColor: containerBackgroundColor,
			width: containerWidth,
			padding: containerPadding ? `${containerPadding.top} ${containerPadding.right} ${containerPadding.bottom} ${containerPadding.left}` : undefined,
			margin: containerMargin ? `${containerMargin.top} ${containerMargin.right} ${containerMargin.bottom} ${containerMargin.left}` : undefined,
			borderStyle: containerBorderStyle !== 'none' ? containerBorderStyle : undefined,
			borderWidth: containerBorderStyle !== 'none' ? containerBorderWidth : undefined,
			borderColor: containerBorderStyle !== 'none' ? containerBorderColor : undefined,
			borderRadius: containerBorderRadius
		}
	});

	return (
		<div {...blockProps}>
			<div
				className="toc-title"
				style={{
					color: titleColor,
					fontSize: titleFontSize,
					fontWeight: titleFontWeight,
					padding: titlePadding ? `${titlePadding.top} ${titlePadding.right} ${titlePadding.bottom} ${titlePadding.left}` : undefined
				}}
			>
				{tocTitle}
			</div>
			<div
				className="toc-content"
				style={{
					color: listColor,
					fontSize: listFontSize
				}}
			>
				{/* Content will be dynamically generated by view.js */}
				<div className="toc-loading">Loading table of contents...</div>
			</div>
		</div>
	);
}

  
	